### ISSUE TITLE
Generate QR codes 404

### ISSUE THREAD

**Issue by Mandera** [MobilePayDev/MobilePayDev.github.io#165]
Hi there,
I'm trying to find a way to print a static QR code for receiving private payments (Without a company).
The QR code in the app seems to be dynamic and I'm guessing temporary.
I found a `Generate QR codes` button [here](https://mobilepaygroup.com/partner/point-of-sale) but it's 404: `https://developer.mobilepay.dk/docs/pos/create-qr-codes`

Is it possible to have the QR code point to something like: `https://qr.mobilepay.fi/p/phone_number`?

Thank you!

**Comment by HenrietteBossen** [comment]
Hi Mandera,
 
We are not that strong in private payments, we only handle the APIs. And with those there are no option for private payments unfortunately. I would recommend that you contact our support directly to get input on this: https://vippsmobilepay.com/help
